openapi: 3.0.1
info:
  description: Move your app forward with the Account Pre-Validation API
  version: "1.0.7-oas3"
  title: Beneficiary account pre-validation
  license:
    name: API Restricted License
    url: 'https://www.swift.com/file/56776/download?token=8w8DC4eF'
paths:
  /v1/accounts/verification:
    post:
      tags:
        - Verify Account
      summary: >-
        Verify that a beneficiary account could be able to receive incoming
        funds.
      description: >
        The service verifies that an account exists at the beneficiary bank and
        is capable of receiving incoming funds. This usually implies that the
        account is open, properly identified by the given number and, depending
        on the  jurisdiction and the market practices in use where the account
        is held, that the creditor name matches the name of the account holder.
        The service provider does not take liability for the response and does
        not provide any guarantee on the outcome of an actual transaction being
        sent to this account. The information provided is meant to be as
        accurate as possible at the time that the request was processed.  The
        requester must pass the creditor name and the service provider can use
        this information as part of the verification or not.
      operationId: VerifyAccount
      parameters:
        - name: LAUApplicationID
          in: header
          description: >-
            ID that identifies the application generating the API and used by
            the gpi Connector to retrieve the related LAU keys, required for
            consumers using gpi connector only
          required: true
          schema:
            type: string
            pattern: '^(?:[a-zA-Z0-9]{1,16})$'
            default: '001'
        - name: LAUVersion
          in: header
          description: >-
            version of the LAUSigned header. Mandatory. "1.0" for this first
            release, required for consumers using gpi connector only
          required: true
          schema:
            type: string
            pattern: '^(?:[1][\.][0])$'
            default: '1.0'
        - name: LAUCallTime
          in: header
          description: >-
            timestamp in UTC of the API call in the format
            YYYY-MM-DDTHH:MM:SS.sssZ, required for consumers using gpi connector
            only
          required: true
          schema:
            type: string
            pattern: >-
              ^(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.[0-9]+)?(?:Z|[+-][01]\d:[0-5]\d)?$
            default: '2018-03-23T15:56:26.728Z'
        - name: LAURequestNonce
          in: header
          description: >-
            a random value generated by the client consumer. Provided with the
            request and copied by the gpi Connector on the response, required
            for consumers using gpi connector only
          required: true
          schema:
            type: string
            pattern: >-
              ^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$
            default: e802ab96-bb3a-4965-9139-5214b9f0f074
        - name: LAUSigned
          in: header
          description: >-
            service specific HTTP headers composed of apiKey, rbac role and bic
            to route the request, required for consumers using gpi connector
            only
          required: true
          schema:
            type: string
            pattern: >-
              ^(?:\(ApplAPIKey=.{1,40}\),\(RBACRole=\[(Update|StandardViewer|FullViewer)\/Scope(\/[a-z]{6,6}[a-z2-9][a-np-z0-9])+\],\(x-bic=[a-z]{6,6}[a-z2-9][a-np-z0-9]\)\))?$
            default: >-
              (ApplAPIKey=yVGhKiV5z1ZGdaqFXoZ8AiSA9n5CrY6B),(RBACRole=[Update/Scope/cclabeb0],(x-bic=cclabeb0))
        - name: LAUSignature
          in: header
          description: >-
            contains the LAU (SHA256) signature, base64 encoded, required for
            consumers using gpi connector only
          required: true
          x-swift-lau-request:
            cryptography: hmac-sha256
            sigBytes: 16
            inputDataPrefix: ':'
            inputDataDelimiter: CRLF
            inputData:
              type: object
              properties:
                LAUApplicationID:
                  type: string
                LAUCallTime:
                  type: string
                LAURequestNonce:
                  type: string
                LAUSigned:
                  type: string
                LAUVersion:
                  type: string
                absPath:
                  type: string
                requestBody:
                  type: string
              required:
                - LAUApplicationID
                - LAUCallTime
                - LAURequestNonce
                - LAUSigned
                - LAUVersion
                - absPath
                - requestBody
          schema:
            type: string
            pattern: >-
              ^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$
            default: U1khA8h9Lm1PqzB99fG6uw==
        - name: x-bic
          in: header
          description: >-
            describe the BIC for SWIFT to route the request, providers get the
            value and consumers are not required to fill it in
          required: false
          schema:
            type: string
            pattern: '^[a-z]{6,6}[a-z2-9][a-np-z0-9]$'
            default: cclabeb0
        - name: SubjectDN
          in: header
          description: >-
            describe the distinguish name of the consumer, providers get the
            value and consumers are not required to fill it in
          required: false
          schema:
            type: string
            default: 'o=cclausb0,o=swift'
        - name: Institution
          in: header
          description: >-
            describe the BIC of the consumer, providers get the value and
            consumers are not required to fill it in
          required: false
          schema:
            type: string
            default: cclausb0
      responses:
        '200':
          description: Get Account Details Response
          headers:
            LAUApplicationID:
              description: >-
                ID that identifies the application generationg the API and used
                by the gpi Connector to retrieve the related LAU keys
              schema:
                type: string
                default: '001'
            LAUVersion:
              description: >-
                version of the LAUSigned header. Mandatory. "1.0" for this first
                release
              schema:
                type: string
                default: '1.0'
            LAUCallTime:
              description: >-
                timestamp in UTC of the API call in the format
                YYYY-MM-DDTHH:MM:SS.sssZ
              schema:
                type: string
                default: '2018-03-23T15:56:27.728Z'
            LAURequestNonce:
              description: >-
                a random value generated by the client. Provided with the
                request and copied by the gpi Connector on the response
              schema:
                type: string
                default: e802ab96-bb3a-4965-9139-5214b9f0f074
            LAUResponseNonce:
              description: a random value generated by the gpi Connector on the response
              schema:
                type: string
                default: 5f1fdf6c-9bbb-4707-bf9e-776e9be878b3
            LAUSignature:
              description: 'contains the LAU signature, base64 ecoded'
              x-swift-lau-response:
                cryptography: hmac-sha256
                sigBytes: 16
                inputDataPrefix: ':'
                inputDataDelimiter: CRLF
                inputData:
                  type: object
                  properties:
                    LAUApplicationID:
                      type: string
                    LAUCallTime:
                      type: string
                    LAURequestNonce:
                      type: string
                    LAUResponseNonce:
                      type: string
                    LAUVersion:
                      type: string
                    responseBody:
                      type: string
                  required:
                    - LAUApplicationID
                    - LAUCallTime
                    - LAURequestNonce
                    - LAUResponseNonce
                    - LAUVersion
                    - responseBody
              schema:
                type: string
                default: U1khA8h9Lm1PqzB99fG6uw==
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountVerificationResponse1'
              examples:
                scenario1_success:
                  description: >-
                    The service provider is in 'scenario 1' (its jurisdiction
                    does not require to verify the creditor name and its
                    implementation does not verify the creditor name). There is
                    an account in the beneficiary bankâ€™s books that is
                    identified by the account identifier (number)  passed in the
                    request and the holder of which corresponds to the given
                    creditor name.  This account is open and capable of
                    receiving funds.
                  value:
                    correlation_identifier: SCENARIO1-CORRID-001
                    response:
                      account_validation_status: PASS
                      creditor_account_match: MTCH
                      creditor_name_match: NOAP
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario1_failure_account_does_match:
                  description: >-
                    The service provider is in 'scenario 1' (its jurisdiction
                    does not require to verify the creditor name and its
                    implementation does not verify the creditor name). The
                    account number provided in the request is not in the
                    beneficiary bankâ€™s books, and thus cannot receive  incoming
                    funds.
                  value:
                    correlation_identifier: SCENARIO1-CORRID-002
                    response:
                      account_validation_status: FAIL
                      creditor_account_match: NMTC
                      creditor_name_match: NOAP
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario1_account_match_but_blocked_for_compliance_reason:
                  description: >-
                    The service provider is in 'scenario 1' (its jurisdiction
                    does not require to verify the creditor name and its
                    implementation does not verify the creditor name). The
                    account number provided in the request is in the beneficiary
                    bankâ€™s books. However the account is  blocked for compliance
                    reasons. The beneficiary bank cannot disclose any
                    information about this state (â€˜no tipping offâ€™).
                  value:
                    correlation_identifier: SCENARIO1-CORRID-003
                    response:
                      account_validation_status: PASS
                      creditor_account_match: MTCH
                      creditor_name_match: NOAP
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario1_account_exists_but_type_does_not_allow_incoming_funds:
                  description: >-
                    The service provider is in 'scenario 1' (its jurisdiction
                    does not require to verify the creditor name and its
                    implementation does not verify the creditor name). The
                    account number provided in the request is in the beneficiary
                    bankâ€™s books. However this type of  account does not allow
                    incoming funds (eg. mortgage account).
                  value:
                    correlation_identifier: SCENARIO1-CORRID-004
                    response:
                      account_validation_status: FAIL
                      creditor_account_match: NMTC
                      creditor_name_match: NOAP
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario1_account_exists_but_closed:
                  description: >-
                    The service provider is in 'scenario 1' (its jurisdiction
                    does not require to verify the creditor name and its
                    implementation does not verify the creditor name). The
                    account number provided in the request is in the beneficiary
                    bankâ€™s books but classified as closed  and thus cannot
                    receive incoming funds.
                  value:
                    correlation_identifier: SCENARIO1-CORRID-005
                    response:
                      account_validation_status: FAIL
                      creditor_account_match: NMTC
                      creditor_name_match: NOAP
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario1_account_matches_but_name_does_match:
                  description: >-
                    The service provider is in 'scenario 1' (its jurisdiction
                    does not require to verify the creditor name and its
                    implementation does not verify the creditor name). The
                    account number provided in the request identifies an account
                    in the beneficiary bankâ€™s books and is in a  state to be the
                    target account of a payment transaction. However the name of
                    the account holder doesnâ€™t match  the one provided in the
                    request.
                  value:
                    correlation_identifier: SCENARIO1-CORRID-006
                    response:
                      account_validation_status: PASS
                      creditor_account_match: MTCH
                      creditor_name_match: NOAP
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario2_success_name_and_account_match:
                  description: >-
                    The service provider is in 'scenario 2' (its jurisdiction
                    does not require to verify the creditor name but its
                    pre-validation implementation verifies the creditor name).
                    There is an account in the beneficiary bankâ€™s books that is
                    identified by the account identifier (number)  passed in the
                    request and the holder of which corresponds to the given
                    creditor name.  This account is open and capable of
                    receiving funds.
                  value:
                    correlation_identifier: SCENARIO2-CORRID-001
                    response:
                      account_validation_status: PASS
                      creditor_account_match: MTCH
                      creditor_name_match: MTCH
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario2_failure_account_does_not_match:
                  description: >-
                    The service provider is in 'scenario 2' (its jurisdiction
                    does not require to verify the creditor name but its
                    pre-validation implementation verifies the creditor name).
                    The account number provided in the request is not in the
                    beneficiary bankâ€™s books, and thus cannot receive  incoming
                    funds.
                  value:
                    correlation_identifier: SCENARIO2-CORRID-002
                    response:
                      account_validation_status: FAIL
                      creditor_account_match: NMTC
                      creditor_name_match: NOAP
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario2_account_match_but_blocked_for_compliance_reason:
                  description: >-
                    The service provider is in 'scenario 2' (its jurisdiction
                    does not require to verify the creditor name but its
                    pre-validation implementation verifies the creditor name).
                    The account number provided in the request is in the
                    beneficiary bankâ€™s books. However the account is  blocked
                    for compliance reasons. The beneficiary bank cannot disclose
                    any information about this state (â€˜no tipping offâ€™).
                  value:
                    correlation_identifier: SCENARIO2-CORRID-003
                    response:
                      account_validation_status: PASS
                      creditor_account_match: MTCH
                      creditor_name_match: MTCH
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario2_account_exists_but_type_does_not_allow_incoming_funds:
                  description: >-
                    The service provider is in 'scenario 2' (its jurisdiction
                    does not require to verify the creditor name but its
                    pre-validation implementation verifies the creditor name).
                    The account number provided in the request is in the
                    beneficiary bankâ€™s books. However this type of  account does
                    not allow incoming funds (eg. mortgage account).
                  value:
                    correlation_identifier: SCENARIO2-CORRID-004
                    response:
                      account_validation_status: FAIL
                      creditor_account_match: NMTC
                      creditor_name_match: NOAP
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario2_account_exists_but_closed:
                  description: >-
                    The service provider is in 'scenario 2' (its jurisdiction
                    does not require to verify the creditor name but its
                    pre-validation implementation verifies the creditor name).
                    The account number provided in the request is in the
                    beneficiary bankâ€™s books but classified as closed  and thus
                    cannot receive incoming funds.
                  value:
                    correlation_identifier: SCENARIO2-CORRID-005
                    response:
                      account_validation_status: FAIL
                      creditor_account_match: NMTC
                      creditor_name_match: NOAP
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario2_account_matches_but_name_does_match:
                  description: >-
                    The service provider is in 'scenario 2' (its jurisdiction
                    does not require to verify the creditor name but its
                    pre-validation implementation verifies the creditor name).
                    The account number provided in the request identifies an
                    account in the beneficiary bankâ€™s books and is in a  state
                    to be the target account of a payment transaction. However
                    the name of the account holder doesnâ€™t match  the one
                    provided in the request.
                  value:
                    correlation_identifier: SCENARIO2-CORRID-006
                    response:
                      account_validation_status: PASS
                      creditor_account_match: MTCH
                      creditor_name_match: NOAP
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario3_success_name_and_account_match:
                  description: >-
                    The service provider is in 'scenario 3' (its jurisdiction
                    requires to verify the creditor name and its pre-validation
                    implementation verifies the creditor name). There is an
                    account in the beneficiary bankâ€™s books that is identified
                    by the account identifier (number)  passed in the request
                    and the holder of which corresponds to the given creditor
                    name.  This account is open and capable of receiving funds.
                  value:
                    correlation_identifier: SCENARIO3-CORRID-001
                    response:
                      account_validation_status: PASS
                      creditor_account_match: MTCH
                      creditor_name_match: MTCH
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario3_failure_account_does_not_match:
                  description: >-
                    The service provider is in 'scenario 3' (its jurisdiction
                    requires to verify the creditor name and its pre-validation
                    implementation verifies the creditor name). The account
                    number provided in the request is not in the beneficiary
                    bankâ€™s books, and thus cannot receive  incoming funds.
                  value:
                    correlation_identifier: SCENARIO3-CORRID-002
                    response:
                      account_validation_status: FAIL
                      creditor_account_match: NMTC
                      creditor_name_match: NOTC
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario3_account_match_but_blocked_for_compliance_reason:
                  description: >-
                    The service provider is in 'scenario 3' (its jurisdiction
                    requires to verify the creditor name and its pre-validation
                    implementation verifies the creditor name). The account
                    number provided in the request is in the beneficiary bankâ€™s
                    books. However the account is  blocked for compliance
                    reasons. The beneficiary bank cannot disclose any
                    information about this state (â€˜no tipping offâ€™).
                  value:
                    correlation_identifier: SCENARIO3-CORRID-003
                    response:
                      account_validation_status: PASS
                      creditor_account_match: MTCH
                      creditor_name_match: MTCH
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario3_account_exists_but_type_does_not_allow_incoming_funds:
                  description: >-
                    The service provider is in 'scenario 3' (its jurisdiction
                    requires to verify the creditor name
                     and its pre-validation implementation verifies the creditor name).
                     The account number provided in the request is in the beneficiary bankâ€™s books. However this type of
                     account does not allow incoming funds (eg. mortgage account).
                  value:
                    correlation_identifier: SCENARIO3-CORRID-004
                    response:
                      account_validation_status: FAIL
                      creditor_account_match: NMTC
                      creditor_name_match: NOTC
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario3_account_exists_but_closed:
                  description: >-
                    The service provider is in 'scenario 3' (its jurisdiction
                    requires to verify the creditor name and its pre-validation
                    implementation verifies the creditor name). The account
                    number provided in the request is in the beneficiary bankâ€™s
                    books but classified as closed  and thus cannot receive
                    incoming funds.
                  value:
                    correlation_identifier: SCENARIO3-CORRID-005
                    response:
                      account_validation_status: FAIL
                      creditor_account_match: NMTC
                      creditor_name_match: NOTC
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario3_account_matches_but_name_does_match:
                  description: >-
                    The service provider is in 'scenario 3' (its jurisdiction
                    requires to verify the creditor name and its pre-validation
                    implementation verifies the creditor name). The account
                    number provided in the request identifies an account in the
                    beneficiary bankâ€™s books and is in a  state to be the target
                    account of a payment transaction. However the name of the
                    account holder doesnâ€™t match  the one provided in the
                    request.
                  value:
                    correlation_identifier: SCENARIO3-CORRID-006
                    response:
                      account_validation_status: PASS
                      creditor_account_match: MTCH
                      creditor_name_match: NOAP
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario4_success_name_and_account_match:
                  description: >-
                    The service provider is in 'scenario 4' (its jurisdiction
                    requires to verify the creditor name but its pre-validation
                    implementation does not verify the creditor name). There is
                    an account in the beneficiary bankâ€™s books that is
                    identified by the account identifier (number)  passed in the
                    request and the holder of which corresponds to the given
                    creditor name.  This account is open and capable of
                    receiving funds.
                  value:
                    correlation_identifier: SCENARIO4-CORRID-001
                    response:
                      account_validation_status: INCO
                      creditor_account_match: MTCH
                      creditor_name_match: NOTC
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario4_failure_account_does_not_match:
                  description: >-
                    The service provider is in 'scenario 4' (its jurisdiction
                    requires to verify the creditor name but its pre-validation
                    implementation does not verify the creditor name). The
                    account number provided in the request is not in the
                    beneficiary bankâ€™s books, and thus cannot receive  incoming
                    funds.
                  value:
                    correlation_identifier: SCENARIO4-CORRID-002
                    response:
                      account_validation_status: FAIL
                      creditor_account_match: NMTC
                      creditor_name_match: NOTC
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario4_account_match_but_blocked_for_compliance_reason:
                  description: >-
                    The service provider is in 'scenario 4' (its jurisdiction
                    requires to verify the creditor name but its pre-validation
                    implementation does not verify the creditor name). The
                    account number provided in the request is in the beneficiary
                    bankâ€™s books. However the account is  blocked for compliance
                    reasons. The beneficiary bank cannot disclose any
                    information about this state (â€˜no tipping offâ€™).
                  value:
                    correlation_identifier: SCENARIO4-CORRID-003
                    response:
                      account_validation_status: INCO
                      creditor_account_match: MTCH
                      creditor_name_match: NOTCH
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario4_account_exists_but_type_does_not_allow_incoming_funds:
                  description: >-
                    The service provider is in 'scenario 4' (its jurisdiction
                    requires to verify the creditor name but its pre-validation
                    implementation does not verify the creditor name). The
                    account number provided in the request is in the beneficiary
                    bankâ€™s books. However this type of  account does not allow
                    incoming funds (eg. mortgage account).
                  value:
                    correlation_identifier: SCENARIO4-CORRID-004
                    response:
                      account_validation_status: FAIL
                      creditor_account_match: NMTC
                      creditor_name_match: NOTC
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario4_account_exists_but_closed:
                  description: >-
                    The service provider is in 'scenario 4' (its jurisdiction
                    requires to verify the creditor name but its pre-validation
                    implementation does not verify the creditor name). The
                    account number provided in the request is in the beneficiary
                    bankâ€™s books but classified as closed  and thus cannot
                    receive incoming funds.
                  value:
                    correlation_identifier: SCENARIO4-CORRID-005
                    response:
                      account_validation_status: FAIL
                      creditor_account_match: NMTC
                      creditor_name_match: NOTC
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
                scenario4_account_matches_but_name_does_match:
                  description: >-
                    The service provider is in 'scenario 4' (its jurisdiction
                    requires to verify the creditor name but its pre-validation
                    implementation does not verify the creditor name). The
                    account number provided in the request identifies an account
                    in the beneficiary bankâ€™s books and is in a  state to be the
                    target account of a payment transaction. However the name of
                    the account holder doesnâ€™t match  the one provided in the
                    request.
                  value:
                    correlation_identifier: SCENARIO4-CORRID-006
                    response:
                      account_validation_status: INCO
                      creditor_account_match: MTCH
                      creditor_name_match: NOTC
                      creditor_address_match: NOAP
                      creditor_organisation_identification_match: NOAP
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCodeConsumer'
              examples:
                scenario_not_allowed:
                  value:
                    status:
                      severity: Fatal
                      code: CANT
                      text: >-
                        service provider is not allowed to provide an answer for
                        this specific account
                scenario_no_integration:
                  value:
                    status:
                      severity: Fatal
                      code: CANT
                      text: >-
                        account requested cannot be verified because unexisting
                        integration with the book system where this account is
                        maintained
                scenario_bad_request:
                  value:
                    status:
                      severity: Fatal
                      code: SwAP501
                      text: API request is malformed
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCodeConsumer'
              examples:
                scenario_invalid_token:
                  value:
                    status:
                      severity: Fatal
                      code: SwAP002
                      text: Invalid OAuth Token
                scenario_bad_request:
                  value:
                    status:
                      severity: Fatal
                      code: SwAP501
                      text: API request is malformed
                scenario_insufficient_scope:
                  value:
                    status:
                      severity: Fatal
                      code: SwAP003
                      text: >-
                        OAuth access token has insufficient scope for the
                        requested service.
                scenario_service_not_provisioned:
                  value:
                    status:
                      severity: Fatal
                      code: SwAP001
                      text: API service not provisioned
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCodeConsumer'
              example:
                status:
                  severity: Fatal
                  code: SwAP506
                  text: Invalid Request. Resource does not exist.
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCodeConsumer'
              example:
                status:
                  severity: Transient
                  code: SwAP507
                  text: >-
                    Request cannot be processed at this time. Please try later.
                    (header Retry-After indicates how long to wait before making
                    a follow-up request)
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCodeConsumer'
              example:
                status:
                  severity: Fatal
                  code: InternalError
                  text: |-
                    Server encountered an unexpected condition and cannot
                        fulfill the request
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCodeConsumer'
              example:
                status:
                  severity: Transient
                  code: SwAP508
                  text: Invalid response received from Service Provider
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCodeConsumer'
              example:
                status:
                  severity: Transient
                  code: SwAP590
                  text: >-
                    Service is temporary unavailable (header Retry-After
                    indicates how long to wait before making a follow-up
                    request)
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCodeConsumer'
              example:
                status:
                  severity: Transient
                  code: SwAP509
                  text: Service Provider time out
      security:
        - SwiftLAU: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountVerificationRequest'
        description: Verify Account Details Request.
        required: true
servers:
  - url: https://apigtw-test.swiftnet.sipn.swift.com/swift-preval-pilot
    description: Pilot environment
  - url: https://apigtw.swiftnet.sipn.swift.com/swift-preval
    description: Production environment
components:
  securitySchemes:
    SwiftLAU:
      type: apiKey
      name: LAUSignature
      in: header
  schemas:
    PostalAddress26:
      type: object
      description: >-
        Information that locates and identifies a specific address, as defined
        by postal services.
      additionalProperties:
        $ref: '#/components/schemas/PostalAddress26'
      properties:
        country:
          description: Nation with its own government.
          $ref: '#/components/schemas/CountryCode'
        address_line:
          type: array
          maxItems: 7
          description: >-
            Information that locates and identifies a specific address, as
            defined by postal services, presented in free format text.
          items:
            $ref: '#/components/schemas/Max70Text'
        post_code:
          description: >-
            Identifier consisting of a group of letters and/or numbers that is
            added to a postal address to assist the sorting of mail.
          $ref: '#/components/schemas/Max16Text'
        town_name:
          description: >-
            Name of a built-up area, with defined boundaries, and a local
            government.
          $ref: '#/components/schemas/Max35Text'
    UUIDv4Identifier:
      type: string
      description: >-
        Universally Unique IDentifier (UUID) version 4, as described in IETC RFC
        4122 "Universally Unique IDentifier (UUID) URN Namespace".
      pattern: '^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$'
    GenericOrganisationIdentification1:
      type: object
      description: Information related to an identification of an organisation.
      additionalProperties:
        $ref: '#/components/schemas/GenericOrganisationIdentification1'
      properties:
        identification:
          description: Identification assigned by an institution.
          $ref: '#/components/schemas/Max35Text'
        scheme_name:
          description: Name of the identification scheme.
          $ref: '#/components/schemas/OrganisationIdentificationSchemeName1Choice'
        issuer:
          description: Entity that assigns the identification.
          $ref: '#/components/schemas/Max35Text'
      required:
        - identification
      example:
        identification: AA1234567890
    AccountValidationCheckContext1Code:
      type: string
      enum:
        - BENR
        - PAYM
        - RFPP
    ExternalClearingSystemIdentification1Code:
      type: string
      description: "Specifies the clearing system identification code, as published in an external clearing system identification code list.\r\nExternal code sets can be downloaded from www.iso20022.org."
    ExternalOrganisationIdentification1Code:
      type: string
      description: "Specifies the external organisation identification scheme name code in the format of character string with a maximum length of 4 characters.\r\nThe list of valid codes is an external code list published separately.\r\nExternal code sets can be downloaded from www.iso20022.org."
    AnyBICIdentifier:
      type: string
      description: >-
        Code allocated to a financial or non-financial institution by the ISO
        9362 Registration Authority, as described in ISO 9362 "Banking - Banking
        telecommunication messages - Business identifier code (BIC)".
      pattern: '^[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}$'
    Max70Text:
      type: string
      description: Specifies a character string with a maximum length of 70characters.
      minLength: 1
      maxLength: 70
    AccountValidationResponse1Code:
      type: string
      enum:
        - NOTC
        - NOAP
        - NMTC
        - MTCH
    AccountValidationResponse2Code:
      type: string
      enum:
        - NMTC
        - MTCH
    AccountValidationResponse3Code:
      type: string
      enum:
        - PASS
        - INCO
        - FAIL
    ValidationCheckReponse1:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ValidationCheckReponse1'
      properties:
        account_validation_status:
          description: Overall status of the account verification.
          $ref: '#/components/schemas/AccountValidationResponse3Code'
        creditor_account_match:
          description: >-
            Whether an account was found in the banks books identified by the
            provided creditor account identification (number) that can receive
            incoming funds.
          $ref: '#/components/schemas/AccountValidationResponse2Code'
        creditor_name_match:
          description: >-
            Result of matching the provided creditor name with the account
            holder name. The matching logic used must follow the same rules as
            the ones that would be apply when the transaction will be processed.
          $ref: '#/components/schemas/AccountValidationResponse1Code'
        creditor_address_match:
          description: >-
            Result of matching the provided creditor address with the account
            holder address. The matching logic used must follow the same rules
            as the ones that would be apply when the transaction will be
            processed.
          $ref: '#/components/schemas/AccountValidationResponse1Code'
        creditor_organisation_identification_match:
          description: >-
            Result of matching the provided creditor organization identification
            with the account holder name. The matching logic used must follow
            the same rules as the ones that would be apply when the transaction
            will be processed.
          $ref: '#/components/schemas/AccountValidationResponse1Code'
      required:
        - account_validation_status
        - creditor_name_match
        - creditor_address_match
        - creditor_organisation_identification_match
    ClearingSystemMemberIdentification2:
      type: object
      description: >-
        Unique identification, as assigned by a clearing system, to
        unambiguously identify a member of the clearing system.
      additionalProperties:
        $ref: '#/components/schemas/ClearingSystemMemberIdentification2'
      properties:
        clearing_system_identification:
          description: >-
            Specification of a pre-agreed offering between clearing agents or
            the channel through which the payment instruction is processed.
          $ref: '#/components/schemas/ClearingSystemIdentification2Choice'
        member_identification:
          description: Identification of a member of a clearing system.
          $ref: '#/components/schemas/Max35Text'
      required:
        - member_identification
    FinancialInstitutionIdentification20:
      type: object
      description: Set of elements used to identify a financial institution.
      additionalProperties:
        $ref: '#/components/schemas/FinancialInstitutionIdentification20'
      properties:
        bicfi:
          description: >-
            Code allocated to a financial institution by the ISO 9362
            Registration Authority as described in ISO 9362 "Banking - Banking
            telecommunication messages - Business identifier code (BIC)".
          $ref: '#/components/schemas/BICFIIdentifier'
        clearing_system_member_identification:
          description: Information used to identify a member within a clearing system.
          $ref: '#/components/schemas/ClearingSystemMemberIdentification2'
    BICFIIdentifier:
      type: string
      description: >-
        Code allocated to a financial institution by the ISO 9362 Registration
        Authority as described in ISO 9362 "Banking - Banking telecommunication
        messages - Business identifier code (BIC)".
      pattern: '^[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}$'
    AccountVerificationRequest:
      type: object
      description: Beneficiary account verification request.
      additionalProperties:
        $ref: '#/components/schemas/AccountVerificationRequest'
      properties:
        correlation_identifier:
          description: >-
            Identifier of the request, assigned by the sender of the request. It
            will allow the requestor to correlate the request and the response.
          $ref: '#/components/schemas/Max50Text'
        context:
          description: Context in which this transaction is performed.
          $ref: '#/components/schemas/AccountValidationCheckContext1Code'
        uetr:
          description: UETR of the transaction that is going to be sent to this account.
          $ref: '#/components/schemas/UUIDv4Identifier'
        creditor_account:
          description: Identifies the account targeted by the transaction.
          $ref: '#/components/schemas/Max34Text'
        creditor_name:
          description: Name by which the creditor is known.
          $ref: '#/components/schemas/Max140Text'
        creditor_address:
          description: >-
            Information that locates and identifies the address of the creditor,
            as defined by postal services.
          $ref: '#/components/schemas/PostalAddress26'
        creditor_organisation_identification:
          description: Unique and unambiguous way to identify a creditor.
          $ref: '#/components/schemas/OrganisationIdentification8'
        creditor_agent:
          description: Financial institution servicing an account for the creditor.
          $ref: '#/components/schemas/FinancialInstitutionIdentification20'
        creditor_agent_branch_identification:
          description: Identifies a specific branch of the creditor.
          $ref: '#/components/schemas/Max35Text'
      required:
        - context
        - creditor_account
        - creditor_name
      example:
        correlation_identifier: CORRID-003
        context: BENR
        uetr: b916a97d-a699-4f20-b8c2-2b07e2684a27
        creditor_account: GB3112000000001987426375
        creditor_name: John Doe
        creditor_address:
          country: GB
        creditor_organisation_identification:
          any_bic: BIC1GB51
    CountryCode:
      type: string
      description: >-
        Code to identify a country, a dependency, or another area of particular
        geopolitical interest, on the basis of country names obtained from the
        United Nations (ISO 3166, Alpha-2 code).
      pattern: '^[A-Z]{2,2}$'
    Max140Text:
      type: string
      description: Specifies a character string with a maximum length of 140 characters.
      minLength: 1
      maxLength: 140
    Max35Text:
      type: string
      description: Specifies a character string with a maximum length of 35 characters.
      minLength: 1
      maxLength: 35
    AccountVerificationResponse1:
      type: object
      description: Beneficiary account verification response.
      additionalProperties:
        $ref: '#/components/schemas/AccountVerificationResponse1'
      properties:
        correlation_identifier:
          description: >-
            Identifier of the request, assigned by the sender of the request. It
            will allow the requestor to correlate the request and the response.
          $ref: '#/components/schemas/Max50Text'
        response:
          description: Provides the response to the account verification request.
          $ref: '#/components/schemas/ValidationCheckReponse1'
      required:
        - response
      example:
        correlation_identifier: CORRID-003
        response:
          account_validation_status: PASS
          creditor_account_match: NMTC
          creditor_name_match: NOTC
          creditor_address_match: NOTC
          creditor_organisation_identification_match: NOTC
    Max16Text:
      type: string
      description: Specifies a character string with a maximum length of 16 characters.
      minLength: 1
      maxLength: 16
    ClearingSystemIdentification2Choice:
      type: object
      description: Choice of a clearing system identifier.
      additionalProperties:
        $ref: '#/components/schemas/ClearingSystemIdentification2Choice'
      properties:
        code:
          description: >-
            Identification of a clearing system, in a coded form as published in
            an external list.
          $ref: '#/components/schemas/ExternalClearingSystemIdentification1Code'
        proprietary:
          description: >-
            Identification code for a clearing system, that has not yet been
            identified in the list of clearing systems.
          $ref: '#/components/schemas/Max35Text'
      maxProperties: 1
      minProperties: 1
    Max34Text:
      type: string
      description: Specifies a character string with a maximum length of 34 characters.
      minLength: 1
      maxLength: 34
    OrganisationIdentification8:
      type: object
      description: Unique and unambiguous way to identify an organisation.
      additionalProperties:
        $ref: '#/components/schemas/OrganisationIdentification8'
      properties:
        any_bic:
          description: >-
            Code allocated to a financial institution or non financial
            institution by the ISO 9362 Registration Authority as described in
            ISO 9362 "Banking - Banking telecommunication messages - Business
            identifier code (BIC)".
          $ref: '#/components/schemas/AnyBICIdentifier'
        other:
          type: array
          description: >-
            Unique identification of an organisation, as assigned by an
            institution, using an identification scheme.
          items:
            $ref: '#/components/schemas/GenericOrganisationIdentification1'
    OrganisationIdentificationSchemeName1Choice:
      type: object
      description: >-
        Sets of elements to identify a name of the organisation identification
        scheme.
      additionalProperties:
        $ref: '#/components/schemas/OrganisationIdentificationSchemeName1Choice'
      properties:
        code:
          description: >-
            Name of the identification scheme, in a coded form as published in
            an external list.
          $ref: '#/components/schemas/ExternalOrganisationIdentification1Code'
        proprietary:
          description: 'Name of the identification scheme, in a free text form.'
          $ref: '#/components/schemas/Max35Text'
      maxProperties: 1
      minProperties: 1
      example:
        code: TXID
    Max50Text:
      type: string
      description: Specifies a character string with a maximum length of 50 characters.
      minLength: 1
      maxLength: 50
    ErrorCodeConsumer:
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/StatusCodeConnector'
    StatusCodeConnector:
      required:
        - code
        - severity
        - text
      properties:
        severity:
          type: string
          enum:
            - Fatal
            - Transient
        code:
          type: string
          enum:
            - SwAP001
            - SwAP002
            - SwAP003
            - SwAP005
            - SwAP006
            - SwAP007
            - SwAP008
            - SwAP010
            - SwAP009
            - SwAP011
            - SwAP099
            - SwAP090
            - SwAP501
            - SwAP504
            - SwAP506
            - SwAP507
            - SwAP521
            - SwAP522
            - SwAP590
            - SwAP591
            - SwAPProxy001
            - SwAPProxy002
            - SwAPProxy003
            - SwAPProxy004
            - SwAPProxy005
            - SwAPProxy006
            - SwAPProxy007
            - SwAPProxy008
            - CANT
            - UNAV
            - InvalidRequest
            - MandatoryFieldMissing
            - MyInstitutionAuthorizationFailure
            - FromAuthorizationFailure
            - NoResultFound
            - UnknownTransaction
            - InvalidRBACRole
            - InternalError
        text:
          type: string
